### ISSUE TITLE
[Bug] ZeroDivisionError

### ISSUE THREAD

**Issue by DhruvalkumarShah** [amine0110/Liver-Segmentation-Using-Monai-and-PyTorch#2]
In utilities.py, at line no. 45 variable name train_step is equal to 0.
While running the code, got a ZeroDivisionError because of line no. 75 which goes as: train_epoch_loss/=train_step.
While running the code, got a ZeroDivisionError because of line no. 80 which goes as: epoch_metric_train/=train_step.

In utilities.py at line no. 93 variable name test_step is equal to 0.
While running the code, got a ZeroDivisionError because of line no. 112 which goes as: test_epoch_loss/=test_step.
While running the code, got a ZeroDivisionError because of line no. 117 which goes as: epoch_metric_test/=test_step.

**Comment by Sawyerbian** [comment]
same error here, it seems because of there's no dataset.
could anybody tell where to download the dataset?

**Comment by amine0110** [comment]
Hi @DhruvalkumarShah ,
Yeah, the step is equal to 0 because your dataloader does not contain any data, @Sawyerbian  is right, you need to download the data, if you have already done that then chech if the folders names are the same as the script and if your patients are zipped or not because if there is something wrong with the path monai will not notify you about that and you will get errors while plotting or starting the training (while calling the dataloader).

**Comment by amine0110** [comment]
Hi @Sawyerbian 

You can get the dataset from kaggle or from here:

http://medicaldecathlon.com/
